package mittwaldv2

// These types were apparently not generated by oapi-codegen, so we need to
// define them ourselves.

type DeMittwaldV1SignupRemovingLastOwnerNotAllowedErrorName string
type DeMittwaldV1SignupSecondFactorRequiredErrorName string

type AppPatchInstallationSystemSoftwareItem = struct {
	SystemSoftwareVersion *string                                    `json:"systemSoftwareVersion,omitempty"`
	UpdatePolicy          *DeMittwaldV1AppSystemSoftwareUpdatePolicy `json:"updatePolicy,omitempty"`
}
type AppPatchInstallationSystemSoftware = map[string]AppPatchInstallationSystemSoftwareItem
