package mittwaldv2

// These types were apparently not generated by oapi-codegen, so we need to
// define them ourselves.

type DeMittwaldV1SignupRemovingLastOwnerNotAllowedErrorName string
type DeMittwaldV1SignupSecondFactorRequiredErrorName string
